export default {
    GET_MOVIES: 'GET_MOVIES',
    GET_MOVIES_IN_PROGRESS: 'GET_MOVIES_IN_PROGRESS',
    GET_MOVIES_ERROR: 'GET_MOVIES_ERROR',
    ADD_TO_FAVS: 'ADD_TO_FAVS',
    REMOVE_FROM_FAVS: 'REMOVE_FROM_FAVS',
    GET_FAVS: 'GET_FAVS'
};